Prepare for ImmaBottom repository

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -29,4 +29,18 @@ if ! pnpm lint; then
     exit 1
 fi
 
+<<<<<<< HEAD
+=======
+# Update commit.json with the latest commit hash
+echo "Updating commit.json with the latest commit hash..."
+COMMIT_HASH=$(git rev-parse HEAD)
+if [ $? -ne 0 ]; then
+    echo "❌ Failed to get commit hash. Ensure you are in a git repository."
+    exit 1
+fi
+
+echo "{ \"commit\": \"$COMMIT_HASH\" }" > app/commit.json
+git add app/commit.json
+
+>>>>>>> 48d3b799435c5f563650cf3ade719ed99182eb8e
 echo "👍 All checks passed! Committing changes..."
